// <auto-generated />
namespace KhodiAsp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_units : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_units));
        
        string IMigrationMetadata.Id
        {
            get { return "202207041823138_update_units"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
