// <auto-generated />
namespace KhodiAsp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateunitstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateunitstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202203051746353_update-units-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
